"""empty message

Revision ID: 05b507d34843
Revises:
Create Date: 2023-07-04 19:55:23.433800

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '05b507d34843'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auctionholder',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_auctionholder_name'), 'auctionholder', ['name'], unique=True)
    op.create_table(
        'region',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_region_name'), 'region', ['name'], unique=True)
    op.create_table(
        'auction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('area', sa.String(length=255), nullable=False),
        sa.Column('site_id', sa.String(length=255), nullable=False),
        sa.Column('region_id', sa.Integer(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'VOIDED',
                'CLOSED',
                'OPEN',
                'CANCELED',
                'TRANSFER',
                'SUSPENDED',
                'NO_DATA',
                name='auctionstatus',
            ),
            nullable=False,
        ),
        sa.Column('auction_date', sa.Date(), nullable=False),
        sa.Column('deadline', sa.Date(), nullable=True),
        sa.Column('participation_fee', sa.Float(), nullable=True),
        sa.Column('auction_holder_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['auction_holder_id'], ['auctionholder.id'], name='fk_auction_asuctionholder'
        ),
        sa.ForeignKeyConstraint(['region_id'], ['region.id'], name='fk_auction_region'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_auction_site_id'), 'auction', ['site_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auction_site_id'), table_name='auction')
    op.drop_table('auction')
    op.drop_index(op.f('ix_region_name'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_auctionholder_name'), table_name='auctionholder')
    op.drop_table('auctionholder')
    # ### end Alembic commands ###
