"""empty message

Revision ID: 9202e16aa7c7
Revises:
Create Date: 2023-06-30 19:24:29.965053

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9202e16aa7c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auctionholder',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'region',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'auction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('area', sa.String(length=255), nullable=False),
        sa.Column('region_id', sa.Integer(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'VOIDED',
                'CLOSED',
                'OPEN',
                'CANCELED',
                'TRANSFER',
                'SUSPENDED',
                'NO_DATA',
                name='auctionstatus',
            ),
            nullable=False,
        ),
        sa.Column('auction_date', sa.Date(), nullable=False),
        sa.Column('deadline', sa.Date(), nullable=False),
        sa.Column('participation_fee', sa.Integer(), nullable=False),
        sa.Column('auction_holder_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['auction_holder_id'], ['auctionholder.id'], name='fk_auction_asuctionholder'
        ),
        sa.ForeignKeyConstraint(['region_id'], ['region.id'], name='fk_auction_region'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction')
    op.drop_table('region')
    op.drop_table('auctionholder')
    # ### end Alembic commands ###
